# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.211
neo_version_range=[21.1.0,)
loader_version_range=[1,)

# Mod
mod_group_id=com.theocreates.createcompression
mod_id=createcompression
mod_name=CreateCompression
mod_license=All Rights Reserved
mod_version=2.0.1
mod_authors=TheoCreates
mod_description=Create addon ported to NeoForge 1.21.1

# Third party versions for 1.21.1
mc_version=1.21.1
jei_version=19.21.2.313
create_version=6.0.6-98
flywheel_version=1.0.4
registrate_version=MC1.21-1.3.0+62
ponder_version=1.0.59
