modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="createcompression"
version="${mod_version}"
displayName="Create Compression"
logoFile="CreateCompression.png"
credits="Special thanks to AndromedaGalaxy29 for art assets"
authors="TheoCreates"
description='''
adds 1-9x compressed versions of blocks, and recipes.
'''

[[dependencies.createcompression]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.createcompression]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
