modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="createcompression"
version="2.0.1"
displayName="Create Compression"
authors="TheoCreates"
description="adds 1-9x compressed versions of blocks, and recipes."

[[dependencies.createcompression]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"

[[dependencies.createcompression]]
modId="minecraft"
type="required"
versionRange="[1.20.1]"
